version: '2'
services:
  redis:
    container_name: ow_redis
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - ./.db/redis:/redis/db
    command: redis-server
  mailhog:
    container_name: ow_mailhog
    image: mailhog/mailhog
    ports: 
      - 1025:1025
      - 8025:8025