/*
@
 This file contains the types constants
@
*/

export const FETCH_EVENTS_REQUEST = "FETCH_EVENTS_REQUEST ";
export const FETCH_EVENTS_SUCCESS = "FETCH_EVENTS_SUCCESS ";
export const FETCH_EVENTS_AFTER_ADDORDELETE_SUCCESS = "FETCH_EVENTS_AFTER_ADDORDELETE_SUCCESS";
export const FETCH_EVENTS_FAILURE = "FETCH_EVENTS_FAILURE ";
export const CREATE_EVENTS_SUCCESS = "CREATE_EVENTS_SUCCESS ";
export const CREATE_EVENTS_REQUEST = "CREATE_EVENTS_REQUEST ";
export const CREATE_EVENTS_FAILURE = "CREATE_EVENTS_FAILURE ";
export const DELETE_EVENTS = "DELETE_EVENTS ";
export const DELETE_EVENTS_FAILURE = "DELETE_EVENTS_FAILURE ";
export const EDIT_EVENTS = "EDIT_EVENTS ";
export const EDIT_EVENTS_FAILURE = "EDIT_EVENTS_FAILURE ";
export const TRACK_CURR = "TRACK_CURR ";



