export const FETCH_NOTIFICATIONS_SUCCESS = "FETCH_NOTIFICATIONS_SUCCESS ";
export const FETCH_NOTIFICATIONS_FAILURE = "FETCH_NOTIFICATIONS_FAILURE ";
export const CREATE_NOTIFICATIONS_SUCCESS = "CREATE_NOTIFICATIONS_SUCCESS ";
export const CREATE_NOTIFICATIONS_FAILURE = "CREATE_NOTIFICATIONS_FAILURE ";
export const DELETE_NOTIFICATIONS_SUCCESS = "DELETE_NOTIFICATIONS_SUCCESS ";
export const DELETE_NOTIFICATIONS_FAILURE = "DELETE_NOTIFICATIONS_FAILURE ";